name: AOSP Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y repo git-core gnupg flex bison build-essential zip curl zlib1g-dev libc6-dev-i386 libncurses5 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig procps
    - name: Build AOSP
      run: |
        df -H
        lscpu
        free -h
        repo init -u https://android.googlesource.com/platform/manifest -b master
        repo sync -j8
        ./device/linaro/dragonboard/fetch-vendor-package.sh
        source ./build/envsetup.sh
        lunch db845c-userdebug
        make -j$(nproc)
